name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
    branches:
      - '*'

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
    - name: Job 1
      run: |
        echo "hello job 1"
        sleep 5

  job2a:
    runs-on: ubuntu-latest

    steps:
    - name: Job 2
      run: |
        echo "hello job 2a"
        sleep 5

  job2b:
    runs-on: ubuntu-latest

    steps:
    - name: Job 2
      run: |
        echo "hello job 2b"
        sleep 5

  job3:
    runs-on: ubuntu-latest
    needs: job2b

    steps:
    - name: Job 3
      run: |
        echo "hello job 3"
        sleep 30

  job4:
    runs-on: ubuntu-latest

    steps:
    - name: Job 4
      if: github.event_name == 'workflow_dispatch'
      run: |
        echo "hello job 4"
        sleep 5
