name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
    branches:
      - '*'

jobs:
  check-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Lint
        id: lint
        run: npm run lint